### ISSUE TITLE
训练精度有确认过吗

### ISSUE THREAD

**Issue by 791136190** [RPFey/UnsuperPoint#2]
想迁移你们的工程到其它框架上，想了解一下你们工程的训练精度有确认过吗

**Comment by RPFey** [comment]
抱歉，这个目前还在研究阶段，我们无法复现原文章中的效果。希望您能指出我们复现代码中的错误。

**Comment by 791136190** [comment]
了解。在另外一个项目“UnSuperPoint_Project”看到有人提出学出来的特征点完全是均匀分布的，不是正确的结果。所以想了解一下你说的不能复现是达不到作者的性能指标，还是完全没办法学出效果？

**Comment by RPFey** [comment]
效果很不理想，可以说完全没办法学出效果，不知道你们情况如何

**Comment by 791136190** [comment]
我们还没在其它框架上开坑，想先确认一下已有的复现情况。如果unSuperPoint复现效果不好，可能需要先选择SuperPoint进行复现

**Comment by SupetZYK** [comment]
请问你们复现的咋样了，我自己复现了一遍，也发现类似的问题，学出来的点近乎均匀分布，topK score的点基本集中在图像的边缘位置。

**Comment by SupetZYK** [comment]
> 请问你们复现的咋样了，我自己复现了一遍，也发现类似的问题，学出来的点近乎均匀分布，topK score的点基本集中在图像的边缘位置。

@791136190 @RPFey

**Comment by 791136190** [comment]
还没有，我们准备在mxnet上复现。还在折腾环境。你是在pytorch上进行的复现？

**Comment by RPFey** [comment]
差不多也是这样，我们打算先看一下 SuperPoint

**Comment by SupetZYK** [comment]
> 还没有，我们准备在mxnet上复现。还在折腾环境。你是在pytorch上进行的复现？

嗯对的，我拿pytorch复现了下，基本和这个code差不多，能跑通，但结果和repo主说的差不多，没发现什么规律。
