### ISSUE TITLE
关于代码合并

### ISSUE THREAD

**Issue by 791136190** [RPFey/UnsuperPoint#3]
你好，我这边花了一点时间测试了一下你们给出的脚本和代码，发现有部分代码实际无法直接运行，我这边做了一些修改，想确认是否可以向你们的工程提交更新。

**Comment by RPFey** [comment]
可以，谢谢您。不过目前我们在研究 SuperPoint, Unsper 这边可能要等一段时间。

**Comment by 791136190** [comment]
> 可以，谢谢您。不过目前我们在研究 SuperPoint, Unsper 这边可能要等一段时间。

明白，我这边做了一些修改，可以得到一个基本效果，和你们之前看到的均匀分布不一样。基本上可以区分出强特征区域和弱特征区域，只是定位还不够准，我这边会继续debug
